<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.5.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Customers\DTOs\" />
    <Folder Include="Customers\Models\" />
    <Folder Include="Database\Configurations\" />
    <Folder Include="Database\Migrations\" />
    <Folder Include="Database\SeedData\" />
    <Folder Include="ProductInventory\DTOs\" />
    <Folder Include="ProductInventory\Models\" />
    <Folder Include="Marketplace\Amazon\" />
    <Folder Include="Marketplace\Flipkart\" />
    <Folder Include="Extensions\" />
    <Folder Include="Orders\Controllers\" />
    <Folder Include="Orders\DTOs\" />
    <Folder Include="Orders\Interfaces\" />
    <Folder Include="Orders\Models\" />
    <Folder Include="Orders\Repositories\" />
    <Folder Include="Orders\Services\" />
    <Folder Include="Products\Controllers\" />
    <Folder Include="Products\Models\" />
    <Folder Include="Products\Services\" />
    <Folder Include="PurchaseOrderItems\NewFolder\" />
    <Folder Include="Purchases\Controllers\" />
    <Folder Include="Purchases\DTOs\" />
    <Folder Include="Purchases\Interfaces\" />
    <Folder Include="Purchases\Models\" />
    <Folder Include="Purchases\Repositories\" />
    <Folder Include="Purchases\Services\" />
    <Folder Include="Sellers\DTOs\" />
    <Folder Include="Sellers\Models\" />
    <Folder Include="SharedKernel\DTOs\" />
    <Folder Include="SharedKernel\Services\" />
    <Folder Include="SharedKernel\Utilities\" />
    <Folder Include="SharedKernel\Validators\" />
    <Folder Include="Suppliers\Models\" />
    <Folder Include="Warehouses\Models\" />
  </ItemGroup>

</Project>
